#!/bin/sh -eux

# XXX defining CC and cross-compiling confuses OpenSSL's build.
unset CC

sudo mkdir /fakeroot
sudo chmod 755 /fakeroot

cat << EOF > /tmp/mingw.cmake
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER i686-w64-mingw32-windres)
SET(CMAKE_FIND_ROOT_PATH /fakeroot)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF

# Build and install libcbor.
git clone --depth=1 https://github.com/pjk/libcbor -b v0.9.0
cd libcbor
mkdir build
(cd build && cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/mingw.cmake \
	-DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/fakeroot ..)
make -j"$(nproc)" -C build
sudo make -C build install
cd ..

# Build and install bearssl.
git clone --depth=1 -b v0.6 https://bearssl.org/git/BearSSL bearssl
cd bearssl
make dll CC=i686-w64-mingw32-gcc LDDLL=i686-w64-mingw32-gcc \
	D=.dll LDDLLFLAGS='-shared -Wl,--out-implib,build/libbearssl.dll.a'
sudo cp build/libbearssl.dll build/libbearssl.dll.a /fakeroot/lib
sudo cp inc/*.h /fakeroot/include
cd -

# Build and install zlib.
git clone --depth=1 https://github.com/madler/zlib -b v1.2.11
cd zlib
make -fwin32/Makefile.gcc PREFIX=i686-w64-mingw32-
sudo make -fwin32/Makefile.gcc PREFIX=i686-w64-mingw32- DESTDIR=/fakeroot \
	INCLUDE_PATH=/include LIBRARY_PATH=/lib BINARY_PATH=/bin install
cd ..

# Build and install libfido2.
export PKG_CONFIG_PATH=/fakeroot/lib/pkgconfig
mkdir build
(cd build && cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/mingw.cmake \
	-DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/fakeroot ..)
make -j"$(nproc)" -C build
sudo make -C build install
