name: bsd

on:
  push:
    branches:
    - master
    - '*-ci'

jobs:
  build:
    if: github.repository == 'Yubico/libfido2'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: [freebsd/12.x, openbsd/6.8]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo apt -q update
        sudo apt install -q -y curl jq
        # install bearssl
        curl -O https://bearssl.org/bearssl-0.6.tar.gz
        tar xzf bearssl-0.6.tar.gz
        cd bearssl-0.6
        make dll
        sudo cp build/libbearssl.so /usr/local/lib
        sudo cp inc/*.h /usr/local/include
    - name: build
      env:
        IMAGE: ${{ matrix.image }}
        SOURCEHUT_TOKEN: ${{ secrets.SOURCEHUT_TOKEN }}
      run: ./.actions/build-bsd
