name: linux

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            cc: gcc-10
          - os: ubuntu-20.04
            cc: clang-12
          - os: ubuntu-20.04
            cc: i686-w64-mingw32-gcc-9
          - os: ubuntu-18.04
            cc: gcc-8
          - os: ubuntu-18.04
            cc: clang-10
          - os: ubuntu-18.04
            cc: i686-w64-mingw32-gcc-7
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      env:
        CC: ${{ matrix.cc }}
      run: |
        sudo apt -q update
        sudo apt install -q -y libcbor-dev libudev-dev libz-dev \
          original-awk mandoc
        if [ "${CC%-*}" == "clang" ]; then
          sudo apt install -q -y ${CC%-*}-tools-${CC#clang-}
        elif [ "${CC%-*}" == "i686-w64-mingw32-gcc" ]; then
          sudo apt install -q -y binutils-mingw-w64-i686 gcc-mingw-w64 \
           g++-mingw-w64 mingw-w64-i686-dev
        else
          sudo apt install -q -y "${CC}"
        fi
        # install bearssl
        curl -O https://bearssl.org/bearssl-0.6.tar.gz
        tar xzf bearssl-0.6.tar.gz
        cd bearssl-0.6
        make dll
        sudo cp build/libbearssl.so /usr/local/lib
        sudo cp inc/*.h /usr/local/include
    - name: build
      env:
        CC: ${{ matrix.cc }}
      run: ./.actions/build-linux-${CC%-*}
